### PR TITLE
Allow instalation using pip

### PR DESCRIPTION
**Pull request by tparker-usgs**
This pull requests adds a setup.py file, allowing pyflit to be installed automatically.

```
$ pip install git+git://github.com/galeo/pyflit
Collecting git+git://github.com/galeo/pyflit
  Cloning git://github.com/galeo/pyflit to /private/var/folders/xf/tgb7k0gs4fbchk8p3v0y9xz00000gn/T/pip-BFBcUC-build
Installing collected packages: pyflit
  Running setup.py install for pyflit ... done
Successfully installed pyflit-1.0
$ 
```

### CODE REVIEW

**Comment by galeo** [comment]
Hi @tparker-usgs ,

I'm sorry but I don't think I want to add a `setup.py`  file to this package. It is not well coded and buggy that should not be used in production.

**Comment by tparker-usgs** [comment]
No worries, thanks for the caution. Do you know of a better way to handle segmented downloads? Is there another package that does it or, if not, things you would do differently if writing pyflit from scratch?

**Comment by galeo** [comment]
I would recommend you to have a look at [pycurl](https://github.com/pycurl/pycurl), which is a thin wrapper above libcurl and have good performance. It's easy to write a segmented downloader that based on it. Here is a simple example: https://github.com/dragondjf/QMusic/blob/master/test/pycurldownload.py.

**Comment by tparker-usgs** [comment]
Thanks!

**Pull request closed without merging**
